apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: priwin99x-go 
  janus-idp.io/tekton: priwin99x-go
  backstage.io/kubernetes-id: priwin99x-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: priwin99x-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml